CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    course VARCHAR(100) NOT NULL
);

ALTER TABLE students ADD COLUMN email VARCHAR(150) NOT NULL;
ALTER TABLE students ADD COLUMN course VARCHAR(100) NOT NULL;
